### ISSUE TITLE
generalization of the amplifier module

### ISSUE THREAD

**Issue by wjtan99** [MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time#10]
Thanks a lot for your great work and shared code. 
I tested your code on a Canon camera raw image and found that the amplifier module works poorly, while the camera final RGM image is very nice.    

This is the output of your mode with external amp=1.0 (the outputs for amp = 2, 5 are way too over exposed) 
![img_num_0_m_1 0](https://user-images.githubusercontent.com/29590928/146572546-a1dbe26e-fa78-4de3-928c-95e9d1599f60.jpg)

This is the camera output  
![IMG_6782](https://user-images.githubusercontent.com/29590928/146572961-9e3e6300-fe62-42b3-bdea-0078471840a2.JPG)

Do you have suggestions on how to improve the amplifier?

**Comment by wjtan99** [comment]
I tested 15 images from normal lighting to very dark lighting. However, the amplifier module gives 1.0 from the function get_na().  Do you have ideas about what may be wrong?  
One problem I found common to many dark image-enhancing algorithms is that, when the lighting is normal, the output is over-exposed. It seems like the algorithms only work on enhancing low-light images.  
Thanks.

**Comment by MohitLamba94** [comment]
Hello @wjtan99,
Thank you for using our project.
In low light there are 3 main problems: 1) Removing noise and getting details 2) Recovering the color 3) Getting the correct brightness.

In our project last one is taken care by the amplifier and first two by the CNN.

The problem with the image you posted is that it is having a color cast and do not feel it is due to the amplifier module as it is responsible for the brightness. Still, if you want to try, the amplifier forces the minimum value to be 1 as seen below,

```
if na1<1.0:
        na1 = np.float32(1.0)
```

Try commenting that out and see if that helps. If that does not the CNN has to be fine-tuned for Canon.

The fact is that details are well recovered. For example see the saturated highlights in the 2nd image, the text and graphics underneath are just not readable. Whereas in the 1st image the saturation is lower highlights are less annoying. Thus even fine-tuning the model I feel will be an overkill.

The problem is in *white balancing* a typical problem with the ISP module of any digital camera and calibration is required to get the proper white.

So what I suggest is simply subject the output of the CNN to some white balancing post processing and things should be fine since only the colors are off. Try out first on Photoshop or GIMP if they can correct the colors. Thereafter shift to python.

Usually when a CNN trained for low light and then tested for bright light images, the usual problem is output is highly saturated. Which is not the case with 1st image otherwise the highlights would have been more problematic. So try some white balancing post processing first.

Hope this helps.
